
######################
### Home Assistant ###
######################

### Additional config files: add_confs/ ###

homeassistant:
  name: Home
  latitude: 40.363608
  longitude: -111.757784
  elevation: 4564
  unit_system: imperial
  time_zone: America/Denver

  customize: !include add_confs/customize.yaml

#logger:
discovery:
frontend:
updater:

recorder:
  purge_interval: 2
  purge_keep_days: 3
  include:
    domains:
      - sensor
      - switch
      - media_player
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date

history:
logbook:
sun:
sensor: !include add_confs/sensors.yaml
zone: !include add_confs/zones.yaml
group: !include add_confs/groups.yaml
scene: !include add_confs/scenes.yaml
#automation: !include add_confs/automation.yaml
script: !include add_confs/scripts.yaml
shell_command: !include add_confs/shell_commands.yaml

http:
  api_password: !secret http_password
  ssl_certificate: /etc/letsencrypt/live/home.jordancarlson.me/fullchain.pem
  ssl_key: /etc/letsencrypt/live/home.jordancarlson.me/privkey.pem
  base_url: home.jordancarlson.me
  login_attempts_threshold: 5

mqtt:
  broker: m11.cloudmqtt.com
  port: 12396
  username: Home Assistant
  password: !secret mqtt_password

notify:
  - name: HTML5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

tts:
  - platform: google

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200

  - platform: nmap_tracker
    home_interval: 10
    hosts: 
     - 192.168.0.104
     - 192.168.0.106

# ecobee:
  # api_key: qzqurGeNiFoo6QpobTVScLX04P6K1w6Q 

zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  polling_interval: 30000
  # device_config:
  #   light.kitchen_dimmer_level:
  #     polling_intensity: 1
  #     refresh_value: true
  #     delay: 2

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.0.112/image/jpeg.cgi
    name: Kitchen Camera

cover:
  - platform: mqtt
    state_topic: "garage/state"
    command_topic: "garage/command"
    name: "Garage Door"
#    retain: true
    payload_open: "SERVICE_OPEN"
    payload_close: "SERVICE_CLOSE"
    state_open: "STATE_OPEN"
    state_closed: "STATE_CLOSED"
#    optimistic: false
#    value_template: '{{ value.x }}'

